apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080   # Access via http://localhost:30080
